# Generated by Django 3.2.19 on 2023-06-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COLLEGE_APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_fname', models.CharField(max_length=200)),
                ('std_email', models.CharField(max_length=25)),
                ('std_hone', models.IntegerField()),
                ('std_address', models.CharField(max_length=25)),
                ('std_image', models.ImageField(null=True, upload_to='image/')),
            ],
        ),
        migrations.RenameField(
            model_name='teachermodel',
            old_name='image',
            new_name='Image',
        ),
    ]
