# Generated by Django 3.2.19 on 2023-06-08 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('COLLEGE_APP', '0002_auto_20230608_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='std_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='COLLEGE_APP.coursemodel'),
        ),
    ]
