# Generated by Django 3.2.19 on 2023-06-09 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COLLEGE_APP', '0003_studentmodel_std_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='std_hone',
            new_name='std_phone',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='std_lname',
            field=models.CharField(default=111, max_length=200),
            preserve_default=False,
        ),
    ]
