# Generated by Django 3.2.19 on 2023-06-09 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('COLLEGE_APP', '0004_auto_20230609_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='std_image',
        ),
    ]
